booktable/urls.py
from django.urls import include, path

from booktable import views

urlpatterns = [
    path('booking/', views.booking, name='booking'),
    path('', views.index, name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booktable.urls')),
]

booktable/models.py
# coding:utf-8
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.db import models


class Table(models.Model):
    TABLE_FORMS = (
        ('rect', 'Rectangular'),
        ('elipse', 'Elipse'),
    )
    
    num = models.PositiveIntegerField(verbose_name='Number', unique=True)
    seats = models.PositiveIntegerField(verbose_name='Seats')
    form = models.CharField(verbose_name='Form', max_length=20, choices=TABLE_FORMS, default='rect')
    coord_x = models.IntegerField(verbose_name='Coordinate X')
    coord_y = models.IntegerField(verbose_name='Coordinate Y')
    size_x = models.IntegerField(verbose_name='Size H')
    size_y = models.IntegerField(verbose_name='Size V')
    
    def __str__(self):
        return '№ {} {}, for {} person(s)'.format(self.num, self.get_form_display(), self.seats)
    
    def clean(self):
        message = {
            'small': 'This table is too small',
            'big': 'This table is too big',
            'out': 'This table is out of room',
        }
        
        errors = {}
        
        if self.size_x < 0:
            errors['size_x'] = message['small']
        if self.size_x > 100:
            errors['size_x'] = message['big']
        if self.size_y < 0:
            errors['size_y'] = message['small']
        if self.size_y > 100:
            errors['size_y'] = message['big']
        
        if self.coord_x < 0:
            errors[NON_FIELD_ERRORS] = message['out']
        if self.coord_y < 0:
            errors[NON_FIELD_ERRORS] = message['out']
        
        if self.coord_x + self.size_x > 100:
            errors[NON_FIELD_ERRORS] = message['out']
        if self.coord_y + self.size_y > 100:
            errors[NON_FIELD_ERRORS] = message['out']
        
        if errors:
            raise ValidationError(errors)


class Booking(models.Model):
    table = models.ForeignKey(Table, verbose_name='Table', on_delete=models.CASCADE)
    date = models.DateField(verbose_name='Date')
    email = models.EmailField(verbose_name='Email')
    
    def __str__(self):
        return '{} @ {}'.format(self.table.num, self.date.strftime('%Y-%m-%d'))
    
    class Meta:
        unique_together = (('table', 'date',),)

booktable/forms.py
# coding:utf-8

import json

from django import forms

from booktable.models import Table

class TableListField(forms.CharField):
    def to_python(self, value):
        value = super().to_python(value)
        value = json.loads(value)
        # import pdb; pdb.set_trace()
        return value


class BookingForm(forms.Form):
    date = forms.DateField()
    name = forms.CharField()
    email = forms.EmailField()
    tables = TableListField()

booktable/views.py
# coding:utf-8

import json

from django.db import transaction
from django.conf import settings
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseNotAllowed
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.dateparse import parse_date

from booktable.models import Booking, Table
from booktable.forms import BookingForm


def index(request):
    table_qs = Table.objects.all()
    return render(request, 'booktable/index.html', {
        'tables': table_qs,
    })

def booking(request):
    if request.method == 'GET':
        try:
            date = parse_date(request.GET.get('date'))
            if not date:
                raise Exception()
        except:
            return HttpResponseBadRequest('Incorrect date')
        booking_qs = Booking.objects.filter(date=date)
        result = [ item.table.num for item in booking_qs ]
        return HttpResponse(json.dumps(result), content_type='application/json')

    elif request.method == 'POST':
        errors = {}

        with transaction.atomic():
            form = BookingForm(request.POST)
            if form.is_valid():
                book_list = []
                for tbl_id in form.cleaned_data['tables']:
                    book_list.append(Booking(table_id=tbl_id, date=form.cleaned_data['date'], email=form.cleaned_data['email']))
            try:
                Booking.objects.bulk_create(book_list)
                message_text = render_to_string('booktable/message.txt', context=form.cleaned_data)
                message_html = render_to_string('booktable/message.html', context=form.cleaned_data)
                send_mail(
                    subject=settings.BOOKTABLE_SUBJECT, 
                    message=message_text, 
                    from_email=settings.BOOKTABLE_EMAIL, 
                    recipient_list=[form.cleaned_data['email']], 
                    html_message=message_html
                )
            except:
                raise
            
            booking_new = []
            booking_qs = Booking.objects.filter(date=form.cleaned_data['date'])
            result = [ item.table.num for item in booking_qs ]
            return HttpResponse(json.dumps(result), content_type='application/json')

    else:
        return HttpResponseNotAllowed(['get', 'post'])

booktable/templates/booktable/index.html
{% load static %}<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Book Table</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'booktable/css/main.css' %}">
    </head>
    <body ng-app="booktable" ng-controller="RoomCtrl">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-xs-9">
                    <h1>Заказывайте наших столов</h1>
                </div>
                <div class="col-xs-3">
                    <div bt-date date="date" class="pull-right" style="margin: 20px 0 10px 0;"></div>
                </div>
            </div>
            
            <div id="room" ng-class="{ less: selected.length }">
                <div ng-repeat="item in tables" 
                     class="room-table"
                     ng-style="table_style(item)"
                     ng-click="click_table(item)"
                ><span class="badge" ng-bind="item.num"></span> for <span ng-bind="item.seats"></span> person(s)</div>
            </div>
        <footer class="footer" ng-if="selected.length">
            <div class="panel panel-default">
                <div class="panel-body form-inline">
                    <div class="form-group">
                        <label for="id_name">Name</label>
                        <input class="form-control" type="text" id="id_name" ng-model="f.name" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input class="form-control" type="email" id="id_email" ng-model="f.email" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary" ng-click="set_booking()">Book selected table(s)</button>
                </div>
            </div>
        </footer>
        </div>
        
        <script type="text/javascript" src="{% static 'js/angular/angular.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'booktable/js/main.js' %}"></script>
        <script type="text/javascript">
        angular.module('booktable').run(function(Tables) {
            {% for item in tables %}
            Tables.data[{{item.num}}] = {
                num: {{ item.num }},
                seats: {{ item.seats }},
                form: '{{ item.form }}',
                coord_x: {{ item.coord_x }},
                coord_y: {{ item.coord_y }},
                size_x: {{ item.size_x }},
                size_y: {{ item.size_y }}
            };
            {% endfor %}
        });
        </script>

        <script type="text/ng-template" id="bt-date.tmpl">
        <div>
            <button ng-click="back()" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-triangle-left"></span>
            </button>
            <span ng-bind="date|date:'yyyy-MM-dd'"></span>
            <button ng-click="forth()" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-triangle-right"></span>
            </button>
        </div>
        </script>
    </body>
</html>

booktable/templates/booktable/message.html
<html>
    <head>
        <meta charset="utf-8"/>
    </head>
    <body>
        <h1>Dear {{ name }}</h1>
        <p>You are successfully booked table(s) {{ tables }} for {{ date|date:'Y-m-d' }}</p>
    </body>
</html>